In [ ]:
print("hi")

hi

# Выгрузка данных

In [1]:
import pandas as pd
import numpy as np

In [2]:
# const_values
travelcard_price = -5000
premium_price = -10000

travel_cashback_limit = 50000
premium_cashback_limit = 100000

In [3]:
clients = pd.read_csv("./data/clients.csv")

In [ ]:
clients.describe()

       client_code        age  avg_monthly_balance_KZT
count    60.000000  60.000000             6.000000e+01
mean     30.500000  37.516667             1.094079e+06
std      17.464249   9.145698             1.417719e+06
min       1.000000  20.000000             4.663000e+04
25%      15.750000  30.000000             8.169800e+04
50%      30.500000  36.500000             1.483350e+05
75%      45.250000  44.000000             1.433970e+06
max      60.000000  58.000000             5.818675e+06

In [ ]:
clients

,client_code,name,status,age,city,avg_monthly_balance_KZT
0,1,Айгерим,Зарплатный клиент,29,Алматы,92643
1,2,Данияр,Премиальный клиент,41,Астана,1577073
2,3,Сабина,Студент,22,Алматы,63116
3,4,Тимур,Зарплатный клиент,36,Караганда,83351
4,5,Камилла,Премиальный клиент,45,Алматы,1336536
5,6,Аян,Стандартный клиент,34,Шымкент,131929
6,7,Руслан,Премиальный клиент,48,Алматы,4040997
7,8,Мадина,Зарплатный клиент,33,Астана,1058403
8,9,Арман,Премиальный клиент,55,Алматы,3084180
9,10,Карина,Зарплатный клиент,38,Усть-Каменогорск,1277325
10,11,Бауржан,Премиальный клиент,50,Павлодар,3230572
11,12,Жанар,Зарплатный клиент,42,Костанай,849046
12,13,Алина,Студент,20,Алматы,54074
13,14,Диас,Зарплатный клиент,27,Астана,57385
14,15,Нурия,Стандартный клиент,31,Шымкент,160778
15,16,Ерасыл,Студент,23,Караганда,46630
16,17,Жанель,Зарплатный клиент,30,Тараз,89126
17,18,Санжар,Стандартный клиент,35,Кызылорда,98089
18,19,Азамат,Зарплатный клиент,32,Алматы,80150
19,20,Анель,Стандартный клиент,28,Астана,141515
20,21,Павел,Премиальный клиент,44,Алматы,1798169
21,22,Аружан,Зарплатный клиент,26,Шымкент,77474
22,23,Темирлан,Стандартный клиент,39,Павлодар,146389
23,24,Гульмира,Зарплатный клиент,41,Усть-Каменогорск,53785
24,25,Адиль,Зарплатный клиент,36,Алматы,55634
25,26,Маржан,Стандартный клиент,33,Астана,136248
26,27,Нурсултан,Зарплатный клиент,29,Караганда,70858
27,28,Алтынай,Стандартный клиент,42,Кызылорда,150281
28,29,Сая,Зарплатный клиент,25,Тараз,88487
29,30,Ербол,Стандартный клиент,40,Павлодар,104553
30,31,Дамир,Зарплатный клиент,34,Алматы,1303848
31,32,Алия,Премиальный клиент,46,Астана,2317160
32,33,Мерей,Зарплатный клиент,31,Шымкент,824246
33,34,Инкар,Стандартный клиент,37,Караганда,115930
34,35,Самат,Премиальный клиент,52,Алматы,1448797
35,36,Назым,Зарплатный клиент,29,Усть-Каменогорск,712277
36,37,Гульнар,Зарплатный клиент,45,Алматы,900361
37,38,Серик,Премиальный клиент,54,Астана,5818675
38,39,Ляззат,Зарплатный клиент,39,Костанай,1248239
39,40,Асхат,Стандартный клиент,43,Павлодар,86092
40,41,Сандугаш,Зарплатный клиент,47,Шымкент,1164313
41,42,Рустем,Премиальный клиент,58,Алматы,2948028
42,43,Нуртас,Зарплатный клиент,28,Астана,76320
43,44,Айнагуль,Стандартный клиент,35,Алматы,89846
44,45,Диана,Зарплатный клиент,27,Караганда,72552
45,46,Арсен,Стандартный клиент,33,Кызылорда,86024
46,47,Камшат,Зарплатный клиент,30,Тараз,79592
47,48,Ержан,Стандартный клиент,38,Павлодар,82214
48,49,Амина,Зарплатный клиент,26,Алматы,1410759
49,50,Тимурлан,Премиальный клиент,42,Астана,3573697
50,51,Жанат,Зарплатный клиент,31,Шымкент,1429027
51,52,Милана,Премиальный клиент,36,Алматы,3418709
52,53,Расул,Зарплатный клиент,29,Караганда,1258584
53,54,Виктория,Премиальный клиент,45,Усть-Каменогорск,4083294
54,55,Асель,Премиальный клиент,49,Алматы,3504443
55,56,Нуркен,Зарплатный клиент,44,Астана,60622
56,57,Жания,Премиальный клиент,52,Павлодар,2757704
57,58,Султан,Зарплатный клиент,40,Караганда,62335
58,59,Динара,Премиальный клиент,55,Алматы,4427461
59,60,Ермек,Зарплатный клиент,42,Кызылорда,48779

In [ ]:
transfers_df = pd.DataFrame()

In [ ]:
transfers_df = []
transactions_df = []

for i in  range(1, 61):
  url_transfer = f"./data/client_{i}_transfers_3m.csv"
  url_transaction = f"./data/client_{i}_transactions_3m.csv"

  transfer = pd.read_csv(url_transfer)
  transfers_df.append(transfer)

  transaction = pd.read_csv(url_transaction)
  transactions_df.append(transaction)

transfers_df = pd.concat(transfers_df)
transactions_df = pd.concat(transactions_df)

In [ ]:
transfers_df

,client_code,name,product,status,city,date,type,direction,amount,currency
0,1,Айгерим,Карта для путешествий,зп,Алматы,2025-06-01 11:40:16,card_out,out,9359.56,KZT
1,1,Айгерим,Карта для путешествий,зп,Алматы,2025-06-02 13:10:59,card_out,out,17590.68,KZT
2,1,Айгерим,Карта для путешествий,зп,Алматы,2025-06-02 20:23:02,card_out,out,19677.33,KZT
3,1,Айгерим,Карта для путешествий,зп,Алматы,2025-06-03 09:50:44,card_out,out,37686.28,KZT
4,1,Айгерим,Карта для путешествий,зп,Алматы,2025-06-03 14:17:12,card_out,out,7880.48,KZT
...,...,...,...,...,...,...,...,...,...,...
295,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,2025-08-28 13:20:22,cashback_in,in,21753.70,KZT
296,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,2025-08-28 17:29:23,atm_withdrawal,out,36981.03,KZT
297,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,2025-08-29 12:49:41,card_out,out,10205.49,KZT
298,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,2025-08-29 15:44:50,card_out,out,28691.97,KZT
299,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,2025-08-30 14:33:54,card_out,out,27152.55,KZT

In [ ]:
transactions_df

,client_code,name,product,status,city,date,category,amount,currency
0,1,Айгерим,Карта для путешествий,зп,Алматы,2025-06-01 09:10:36,Такси,6424.48,KZT
1,1,Айгерим,Карта для путешествий,зп,Алматы,2025-06-01 09:15:49,Такси,2643.90,KZT
2,1,Айгерим,Карта для путешествий,зп,Алматы,2025-06-01 13:10:49,Смотрим дома,4716.59,KZT
3,1,Айгерим,Карта для путешествий,зп,Алматы,2025-06-01 15:40:10,Такси,3669.43,KZT
4,1,Айгерим,Карта для путешествий,зп,Алматы,2025-06-01 17:40:30,Играем дома,5095.03,KZT
...,...,...,...,...,...,...,...,...,...
295,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,2025-08-31 11:20:39,Кафе и рестораны,3489.42,KZT
296,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,2025-08-31 12:10:15,Продукты питания,8255.46,KZT
297,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,2025-08-31 17:00:58,Кафе и рестораны,4951.28,KZT
298,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,2025-08-31 18:30:27,АЗС,15879.48,KZT
299,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,2025-08-31 19:00:50,Кафе и рестораны,4977.46,KZT

# Мини анализ

In [ ]:
transactions_df['status'].value_counts() / 300

status
Зарплатный клиент     15.0
зп                    13.0
Премиальный клиент    10.0
обычный                8.0
вип                    6.0
Стандартный клиент     5.0
студент                3.0
Name: count, dtype: float64

In [ ]:
transactions_df['city'].value_counts() / 300

city
Алматы              18.0
Астана              10.0
Караганда            7.0
Шымкент              6.0
Павлодар             6.0
Усть-Каменогорск     4.0
Кызылорда            4.0
Тараз                3.0
Костанай             2.0
Name: count, dtype: float64

In [ ]:
transactions_df['product'].value_counts() / 300

product
Карта для путешествий     6.0
Премиальная карта         6.0
Кредитная карта           6.0
Обмен валют               6.0
Кредит наличными          6.0
Депозит Мультивалютный    6.0
Депозит Сберегательный    6.0
Депозит Накопительный     6.0
Инвестиции                6.0
Золотые слитки            6.0
Name: count, dtype: float64

In [ ]:
transactions_df[transactions_df['currency'] == 'EUR']

,client_code,name,product,status,city,date,category,amount,currency
229,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-12 06:30:06,Такси,2.43,EUR
230,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-12 09:00:28,Путешествия,224.71,EUR
231,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-12 09:05:20,Кафе и рестораны,11.18,EUR
232,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-12 10:20:41,Такси,3.10,EUR
233,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-12 12:00:45,Такси,4.07,EUR
235,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-12 15:30:19,Развлечения,8.85,EUR
237,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-12 19:40:46,Кафе и рестораны,15.61,EUR
238,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-12 22:30:50,Отели,17.55,EUR
240,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-13 09:05:57,Кафе и рестораны,7.34,EUR
241,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-13 10:20:40,Такси,8.43,EUR
243,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-13 15:30:41,Развлечения,10.57,EUR
244,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-13 19:40:04,Кафе и рестораны,10.07,EUR
245,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-13 22:30:57,Отели,30.39,EUR
246,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-14 09:05:17,Кафе и рестораны,6.78,EUR
247,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-14 10:20:30,Такси,3.10,EUR
248,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-14 14:10:11,Кино,4.60,EUR
250,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-14 19:40:40,Кафе и рестораны,16.28,EUR
251,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-14 22:30:26,Отели,19.65,EUR
252,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-15 10:20:29,Такси,5.36,EUR
253,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-15 14:10:37,Кино,5.87,EUR
254,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-15 19:40:47,Кафе и рестораны,10.13,EUR
255,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-15 22:30:10,Отели,19.83,EUR
256,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-16 09:05:46,Кафе и рестораны,23.42,EUR
257,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-16 10:20:44,Такси,3.52,EUR
258,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-16 15:30:42,Развлечения,4.30,EUR
259,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-16 19:40:53,Кафе и рестораны,8.77,EUR
260,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-16 22:30:56,Отели,31.36,EUR
261,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-17 09:05:06,Кафе и рестораны,23.08,EUR
262,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-17 10:20:27,Такси,5.08,EUR
263,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-17 15:30:27,Развлечения,14.74,EUR
264,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-17 16:00:35,Такси,5.11,EUR
265,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-17 19:00:54,Путешествия,556.44,EUR
267,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-17 19:40:02,Кафе и рестораны,17.09,EUR
269,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-17 21:20:05,Такси,5.40,EUR
270,3,Сабина,Карта для путешествий,студент,Алматы,2025-08-17 22:30:14,Отели,35.26,EUR

In [ ]:
transfers_df['currency'].value_counts() / 300

currency
KZT    60.0
Name: count, dtype: float64

In [ ]:
transfers_df['type'].value_counts()

type
card_out                   8829
p2p_out                    3600
atm_withdrawal             1152
card_in                     981
utilities_out               918
loan_payment_out            612
cashback_in                 540
refund_in                   360
fx_buy                      216
salary_in                   171
invest_out                  144
installment_payment_out     108
deposit_topup_out           108
cc_repayment_out            108
fx_sell                      54
invest_in                    36
gold_buy_out                 18
family_in                    18
gold_sell_in                 18
stipend_in                    9
Name: count, dtype: int64

# Конвертация валют

In [ ]:
transactions_df['currency'].unique()

array(['KZT', 'EUR'], dtype=object)

In [ ]:
transactions_df['date'] = pd.to_datetime(transactions_df['date']).dt.strftime('%d.%m.%Y')
transfers_df['date'] = pd.to_datetime(transfers_df['date']).dt.strftime('%d.%m.%Y')

In [ ]:
exchange_rate = pd.read_excel("./Foreign_Exchange_Rates.xlsx")
exchange_rate = exchange_rate.set_index('Date')

In [ ]:
exchange_rate['KZT'] = 1

In [ ]:
transactions_df['converted_amount'] = transactions_df.apply(lambda x: exchange_rate.loc[x['date']][x['currency']] * x['amount'], axis=1)
transfers_df['converted_amount'] = transfers_df.apply(lambda x: exchange_rate.loc[x['date']][x['currency']] * x['amount'], axis=1)

# Рассчет purchases, balance, deposit

In [ ]:
transactions_df['category'].unique()

array(['Такси', 'Смотрим дома', 'Играем дома', 'Продукты питания',
       'Едим дома', 'Кафе и рестораны', 'АЗС', 'Кино', 'Путешествия',
       'Отели', 'Развлечения', 'Косметика и Парфюмерия', 'Подарки',
       'Спорт', 'Ремонт дома', 'Мебель', 'Одежда и обувь',
       'Ювелирные украшения', 'Авто'], dtype=object)

In [ ]:
transactions_df['date_m'] = transactions_df['date'].str[3:]
transfers_df['date_m'] = transfers_df['date'].str[3:]

In [ ]:
purchases = transactions_df.groupby(['client_code', 'date_m'])['converted_amount'].sum()

In [ ]:
deposits = transfers_df[transfers_df['type'] == 'deposit_topup_out'].groupby(['client_code', 'date_m'])['converted_amount'].sum()

In [ ]:
transfers_df

,client_code,name,product,status,city,date,type,direction,amount,currency,converted_amount,date_m
0,1,Айгерим,Карта для путешествий,зп,Алматы,01.06.2025,card_out,out,9359.56,KZT,9359.56,06.2025
1,1,Айгерим,Карта для путешествий,зп,Алматы,02.06.2025,card_out,out,17590.68,KZT,17590.68,06.2025
2,1,Айгерим,Карта для путешествий,зп,Алматы,02.06.2025,card_out,out,19677.33,KZT,19677.33,06.2025
3,1,Айгерим,Карта для путешествий,зп,Алматы,03.06.2025,card_out,out,37686.28,KZT,37686.28,06.2025
4,1,Айгерим,Карта для путешествий,зп,Алматы,03.06.2025,card_out,out,7880.48,KZT,7880.48,06.2025
...,...,...,...,...,...,...,...,...,...,...,...,...
295,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,28.08.2025,cashback_in,in,21753.70,KZT,21753.70,08.2025
296,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,28.08.2025,atm_withdrawal,out,36981.03,KZT,36981.03,08.2025
297,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,29.08.2025,card_out,out,10205.49,KZT,10205.49,08.2025
298,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,29.08.2025,card_out,out,28691.97,KZT,28691.97,08.2025
299,60,Ермек,Золотые слитки,Зарплатный клиент,Кызылорда,30.08.2025,card_out,out,27152.55,KZT,27152.55,08.2025

In [ ]:
transfers_df.loc[transfers_df['type'] == 'invest_in', 'converted_amount'] *= -1

In [ ]:
invest = transfers_df[transfers_df['type'].isin(['invest_out', 'invest_in'])].groupby(['client_code', 'date_m'])['converted_amount'].sum()

In [ ]:
transfers_df.loc[transfers_df['type'] == 'invest_in', 'converted_amount'] *= -1

In [ ]:
client_info = clients[['client_code', 'avg_monthly_balance_KZT']]

In [ ]:
purchases_deposits = pd.merge(purchases, deposits, on=['client_code', 'date_m'], how='outer')
purchases_deposits = pd.merge(purchases_deposits, invest, on=['client_code', 'date_m'], how='outer')
purchases_deposits.reset_index(inplace=True)

In [ ]:
client_info = pd.merge(purchases_deposits, client_info, on='client_code', how='outer')
client_info.fillna(0, inplace=True)

In [ ]:
client_info.rename(columns={'converted_amount_x': 'purchase', 'converted_amount_y': 'deposit', 'converted_amount': 'invest'}, inplace=True)

In [ ]:
client_info

,client_code,date_m,purchase,deposit,invest,avg_monthly_balance_KZT
0,1,06.2025,770614.49,0.0,0.0,92643
1,1,07.2025,1118856.15,0.0,0.0,92643
2,1,08.2025,737443.63,0.0,0.0,92643
3,2,06.2025,816950.52,0.0,0.0,1577073
4,2,07.2025,805705.74,0.0,0.0,1577073
...,...,...,...,...,...,...
175,59,07.2025,1001491.63,0.0,0.0,4427461
176,59,08.2025,979019.84,0.0,0.0,4427461
177,60,06.2025,738528.33,0.0,0.0,48779
178,60,07.2025,788044.31,0.0,0.0,48779
179,60,08.2025,773209.04,0.0,0.0,48779

# Card costs

In [ ]:
client_info["travelcard_cost"] = client_info.apply(
    lambda x: 0 if (x['purchase'] >= 500000
                    or x['avg_monthly_balance_KZT'] > 3000000
                    or x['deposit'] > 3000000)
    else travelcard_price,
    axis=1
)

In [ ]:
client_info["premium_cost"] = client_info.apply(
    lambda x: 0 if (x['purchase'] >= 1000000
                    or x['avg_monthly_balance_KZT'] > 15000000
                    or x['deposit'] > 15000000)
    else premium_price,
    axis=1
)

In [ ]:
client_info["credit_card"] = 0

# Travel card cashback

In [ ]:
travel_cashback_4percent = ['Путешествия', 'Tакси', 'Поезда', 'Самолеты', 'Авиабилеты', 'Отели', 'Аренда авто', 'Авто']

In [ ]:
travel_cashback = transactions_df[transactions_df['category'].isin(travel_cashback_4percent)].groupby(['client_code', 'date_m'])['converted_amount'].sum()
travel_cashback *= 0.04
travel_cashback.rename('travel_cashback', inplace=True)

client_code  date_m
1            06.2025     1584.945600
             07.2025    14795.886000
2            08.2025     8918.985200
3            08.2025    23635.111296
4            08.2025    14667.295600
5            08.2025    14224.092800
6            08.2025    12553.480800
13           07.2025     5121.640000
16           07.2025     6044.973600
26           08.2025    16883.829200
27           08.2025    10935.824800
28           08.2025    11801.836000
29           08.2025    10885.043600
30           08.2025    12955.011600
45           06.2025    11964.938800
             07.2025     3425.290800
             08.2025     9133.222800
47           08.2025     6963.050000
49           08.2025    14542.719600
54           08.2025    27863.086800
56           08.2025    14833.789200
Name: travel_cashback, dtype: float64

In [ ]:
client_info = pd.merge(client_info, travel_cashback, on=['client_code', 'date_m'], how='outer')
client_info.fillna(0, inplace=True)

In [ ]:
client_info['travel_cashback'].unique()

array([ 1584.9456  , 14795.886   ,     0.      ,  8918.9852  ,
       23635.111296, 14667.2956  , 14224.0928  , 12553.4808  ,
        5121.64    ,  6044.9736  , 16883.8292  , 10935.8248  ,
       11801.836   , 10885.0436  , 12955.0116  , 11964.9388  ,
        3425.2908  ,  9133.2228  ,  6963.05    , 14542.7196  ,
       27863.0868  , 14833.7892  ])

# Premium cashback

In [ ]:
vklad = client_info.groupby(['client_code'])['deposit'].sum() + client_info.groupby(['client_code'])['invest'].sum()

In [ ]:
percent = np.select(
    [
        vklad >= 6000000,
        vklad >= 1000000
    ],
    [
        0.04,
        0.03
    ],
    default=0.02
)

percent = pd.Series(percent, index=vklad.index, name="percent")

In [ ]:
premium_cashback = transactions_df.groupby(['client_code', 'date_m'])['converted_amount'].sum()
premium_cashback = (
    premium_cashback *
    premium_cashback.index.get_level_values(0).map(percent).fillna(0.02)
)
premium_cashback.rename('premium_cashback', inplace=True)

client_code  date_m
1            06.2025    15412.2898
             07.2025    22377.1230
             08.2025    14748.8726
2            06.2025    16339.0104
             07.2025    16114.1148
                           ...
59           07.2025    20029.8326
             08.2025    19580.3968
60           06.2025    14770.5666
             07.2025    15760.8862
             08.2025    15464.1808
Name: premium_cashback, Length: 180, dtype: float64

In [ ]:
client_info = pd.merge(client_info, premium_cashback, on=['client_code', 'date_m'], how='outer')
client_info.fillna(0, inplace=True)

# Credit card cashback

In [ ]:
credit_card_cashback = (
    transactions_df
    .groupby(['client_code', 'date_m'])
    .apply(lambda g: g[['category', 'converted_amount']]
                   .groupby('category')['converted_amount']
                   .sum()
                   .nlargest(3)
                   .sum())
)
credit_card_cashback.rename('credit_card_cashback', inplace=True)

/tmp/ipython-input-1383919679.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g[['category', 'converted_amount']]

client_code  date_m
1            06.2025    474228.12
             07.2025    650310.66
             08.2025    437614.47
2            06.2025    575664.43
             07.2025    518925.89
                          ...
59           07.2025    684914.61
             08.2025    687951.07
60           06.2025    474558.14
             07.2025    531761.85
             08.2025    530872.64
Name: credit_card_cashback, Length: 180, dtype: float64

In [ ]:
credit_card_cashback *= 0.1

In [ ]:
client_info = pd.merge(client_info, credit_card_cashback, on=['client_code', 'date_m'], how='outer')
client_info.fillna(0, inplace=True)

In [ ]:
client_info['travel_cashback'] = client_info['travel_cashback'].apply(lambda x: min(x, travel_cashback_limit))
client_info['premium_cashback'] = client_info['premium_cashback'].apply(lambda x: min(x, premium_cashback_limit))

# Transfers

In [ ]:
transfers_df['type'].unique()

array(['card_out', 'p2p_out', 'atm_withdrawal', 'utilities_out',
       'cashback_in', 'loan_payment_out', 'card_in', 'salary_in',
       'refund_in', 'family_in', 'stipend_in', 'installment_payment_out',
       'cc_repayment_out', 'fx_buy', 'fx_sell', 'deposit_topup_out',
       'invest_out', 'invest_in', 'gold_buy_out', 'gold_sell_in'],
      dtype=object)

In [ ]:
import pandas as pd

invest_ops = ['invest_out', 'invest_in']
fx_ops = ['fx_buy', 'fx_sell']
gold_ops = ['gold_buy_out', 'gold_sell_in']
credit_ops = ['loan_payment_out', 'cc_repayment_out', 'installment_payment_out']

agg_df = (
    transfers_df
    .groupby(['client_code', 'date_m'])
    .apply(lambda g: pd.Series({
        'invest_sum': g.loc[g['type']=='invest_out', 'converted_amount'].sum()
                      - g.loc[g['type']=='invest_in', 'converted_amount'].sum(),
        'invest_count': g[g['type'].isin(invest_ops)].shape[0],

        'fx_sum': g[g['type'].isin(fx_ops)]['converted_amount'].sum(),
        'fx_count': g[g['type'].isin(fx_ops)].shape[0],

        'gold_sum': g[g['type'].isin(gold_ops)]['converted_amount'].sum(),
        'gold_count': g[g['type'].isin(gold_ops)].shape[0],

        'credit_count': g[g['type'].isin(credit_ops)].shape[0]
    }))
)

                     invest_sum  invest_count  fx_sum  fx_count  gold_sum  \
client_code date_m
1           06.2025         0.0           0.0     0.0       0.0       0.0
            07.2025         0.0           0.0     0.0       0.0       0.0
            08.2025         0.0           0.0     0.0       0.0       0.0
2           06.2025         0.0           0.0     0.0       0.0       0.0
            07.2025         0.0           0.0     0.0       0.0       0.0

                     gold_count  credit_count
client_code date_m
1           06.2025         0.0           3.0
            07.2025         0.0           3.0
            08.2025         0.0           3.0
2           06.2025         0.0           3.0
            07.2025         0.0           3.0

/tmp/ipython-input-3048643447.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({

In [ ]:
client_info = pd.merge(client_info, agg_df, on=['client_code', 'date_m'], how='outer')
client_info.fillna(0, inplace=True)

# Clusters

In [ ]:
client_info

,client_code,date_m,purchase,deposit,invest,avg_monthly_balance_KZT,travelcard_cost,premium_cost,credit_card,travel_cashback,premium_cashback,credit_card_cashback,invest_sum,invest_count,fx_sum,fx_count,gold_sum,gold_count,credit_count
0,1,06.2025,770614.49,0.0,0.0,92643,0,-10000,0,1584.9456,15412.2898,47422.812,0.0,0.0,0.0,0.0,0.00,0.0,3.0
1,1,07.2025,1118856.15,0.0,0.0,92643,0,0,0,14795.8860,22377.1230,65031.066,0.0,0.0,0.0,0.0,0.00,0.0,3.0
2,1,08.2025,737443.63,0.0,0.0,92643,0,-10000,0,0.0000,14748.8726,43761.447,0.0,0.0,0.0,0.0,0.00,0.0,3.0
3,2,06.2025,816950.52,0.0,0.0,1577073,0,-10000,0,0.0000,16339.0104,57566.443,0.0,0.0,0.0,0.0,0.00,0.0,3.0
4,2,07.2025,805705.74,0.0,0.0,1577073,0,-10000,0,0.0000,16114.1148,51892.589,0.0,0.0,0.0,0.0,0.00,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,59,07.2025,1001491.63,0.0,0.0,4427461,0,0,0,0.0000,20029.8326,68491.461,0.0,0.0,0.0,0.0,2307848.09,2.0,3.0
176,59,08.2025,979019.84,0.0,0.0,4427461,0,-10000,0,0.0000,19580.3968,68795.107,0.0,0.0,0.0,0.0,1789511.39,2.0,3.0
177,60,06.2025,738528.33,0.0,0.0,48779,0,-10000,0,0.0000,14770.5666,47455.814,0.0,0.0,0.0,0.0,2496431.57,2.0,3.0
178,60,07.2025,788044.31,0.0,0.0,48779,0,-10000,0,0.0000,15760.8862,53176.185,0.0,0.0,0.0,0.0,2298275.06,2.0,3.0
179,60,08.2025,773209.04,0.0,0.0,48779,0,-10000,0,0.0000,15464.1808,53087.264,0.0,0.0,0.0,0.0,2351403.96,2.0,3.0

In [ ]:
client_info_final = client_info.copy()

In [ ]:
client_info_final['premium_cashback'] = client_info_final['premium_cost'] + client_info_final['premium_cashback']
client_info_final['travel_cashback'] = client_info_final['travel_cashback'] + client_info_final['travel_cashback']

In [ ]:
client_info_final.drop(columns=['date_m', 'purchase', 'travelcard_cost', 'premium_cost', 'credit_card', 'invest_sum', 'invest_count', 'fx_sum', 'gold_sum'], inplace=True)

In [ ]:
client_info_final

,client_code,deposit,invest,avg_monthly_balance_KZT,travel_cashback,premium_cashback,credit_card_cashback,fx_count,gold_count,credit_count
0,1,0.0,0.0,92643,3169.8912,5412.2898,47422.812,0.0,0.0,3.0
1,1,0.0,0.0,92643,29591.7720,22377.1230,65031.066,0.0,0.0,3.0
2,1,0.0,0.0,92643,0.0000,4748.8726,43761.447,0.0,0.0,3.0
3,2,0.0,0.0,1577073,0.0000,6339.0104,57566.443,0.0,0.0,3.0
4,2,0.0,0.0,1577073,0.0000,6114.1148,51892.589,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...
175,59,0.0,0.0,4427461,0.0000,20029.8326,68491.461,0.0,2.0,3.0
176,59,0.0,0.0,4427461,0.0000,9580.3968,68795.107,0.0,2.0,3.0
177,60,0.0,0.0,48779,0.0000,4770.5666,47455.814,0.0,2.0,3.0
178,60,0.0,0.0,48779,0.0000,5760.8862,53176.185,0.0,2.0,3.0
179,60,0.0,0.0,48779,0.0000,5464.1808,53087.264,0.0,2.0,3.0

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

client_features = (
    client_info_final
    .groupby('client_code')
    .mean(numeric_only=True)
    .reset_index()
)

X = client_features.drop(columns=['client_code'])
X_scaled = StandardScaler().fit_transform(X)

kmeans = KMeans(n_clusters=10, random_state=42, n_init=10)
client_features['cluster'] = kmeans.fit_predict(X_scaled)

client_features.head()

,client_code,deposit,invest,avg_monthly_balance_KZT,travel_cashback,premium_cashback,credit_card_cashback,fx_count,gold_count,credit_count,cluster
0,1,0.0,0.0,92643.0,10920.554400,10846.095133,52071.775000,0.0,0.0,3.0,0
1,2,0.0,0.0,1577073.0,5945.990133,10821.815467,56959.811000,0.0,0.0,3.0,0
2,3,0.0,0.0,63116.0,15756.740864,9207.645481,50583.809517,0.0,0.0,3.0,0
3,4,0.0,0.0,83351.0,9778.197067,10273.289467,51641.825667,0.0,0.0,3.0,0
4,5,0.0,0.0,1336536.0,9482.728533,11357.806667,51322.353667,0.0,0.0,3.0,0

In [ ]:
cluster_profile = (
    client_features
    .groupby('cluster')
    .mean(numeric_only=True)
)

cluster_profile['num_clients'] = client_features.groupby('cluster').size()

cluster_profile

,client_code,deposit,invest,avg_monthly_balance_KZT,travel_cashback,premium_cashback,credit_card_cashback,fx_count,gold_count,credit_count,num_clients
cluster,,,,,,,,,,,
0,14.636364,0.000000,0.000000,3.486432e+05,9323.717727,10472.812613,54241.842077,0.0,0.0,3.909091,11
1,29.307692,0.000000,0.000000,8.495778e+05,0.000000,7792.015836,56034.127590,0.0,0.0,3.615385,13
2,57.500000,0.000000,0.000000,1.810224e+06,1648.198800,10333.209533,63290.537778,0.0,2.0,3.000000,6
3,45.000000,501575.033333,0.000000,7.255200e+04,16348.968267,92494.629333,132007.470333,0.0,0.0,3.000000,1
4,51.000000,0.000000,950504.240667,2.218155e+06,1939.029280,19093.446087,61556.058933,0.0,0.0,3.000000,5
5,15.500000,0.000000,0.000000,8.434700e+04,1240.734844,3574.162022,42332.015889,0.0,0.0,15.000000,6
6,21.500000,0.000000,0.000000,3.829137e+05,0.000000,5378.867378,50945.627944,15.0,0.0,3.000000,6
7,23.166667,0.000000,0.000000,3.573269e+06,0.000000,15789.101178,68681.184444,0.0,0.0,4.000000,6
8,45.600000,450727.698000,0.000000,8.279920e+04,928.406667,13146.316960,51094.908400,0.0,0.0,3.000000,5
9,54.000000,0.000000,918643.876667,4.083294e+06,18575.391200,38693.934200,94186.760667,0.0,0.0,3.000000,1

# Logic

In [ ]:
client_info['premium_cashback'] = client_info['premium_cost'] + client_info['premium_cashback']
client_info['travel_cashback'] = client_info['travelcard_cost'] + client_info['travel_cashback']

client_info.drop(columns=['travelcard_cost', 'premium_cost', 'credit_card'], inplace=True)

In [ ]:
client_info_sm = client_info.drop(columns=['date_m']).groupby('client_code').sum()

In [ ]:
transfers_df['product'].unique()

array(['Карта для путешествий', 'Премиальная карта', 'Кредитная карта',
       'Обмен валют', 'Кредит наличными', 'Депозит Мультивалютный',
       'Депозит Сберегательный', 'Депозит Накопительный', 'Инвестиции',
       'Золотые слитки'], dtype=object)

In [ ]:
vip = ['Золотые слитки', 'Инвестиции', 'Депозит Накопительный', 'card']
valut = ['Обмен валют', 'card']
middle = ['Инвестиции', 'Депозит Сберегательный', 'card']
standart = ['Кредит наличными', 'Депозит Мультивалютный', 'card']

In [ ]:
clients['status'].unique()

array(['Зарплатный клиент', 'Премиальный клиент', 'Студент',
       'Стандартный клиент'], dtype=object)

In [ ]:
client_info_sm = pd.merge(client_info_sm, clients[['client_code', 'status']], on=['client_code'], how='left')

In [ ]:
client_info_sm['credit_card_cashback'] = client_info_sm['credit_card_cashback'].apply(lambda x: min(x, 240000))

In [ ]:

cashback_cols = ['travel_cashback', 'premium_cashback', 'credit_card_cashback']

client_info_sm['cashback'] = client_info_sm[cashback_cols].max(axis=1)

client_info_sm['card'] = client_info_sm[cashback_cols].idxmax(axis=1)

name_map = {
    'travel_cashback': 'Карта для путешествий',
    'premium_cashback': 'Премиальная карта',
    'credit_card_cashback': 'Кредитная карта'
}

client_info_sm['card'] = client_info_sm['card'].map(name_map)

In [ ]:
client_info_sm.drop(columns=['travel_cashback', 'premium_cashback', 'credit_card_cashback'], inplace=True)

In [ ]:
client_info_sm['fx_count'].value_counts()

fx_count
0.0     54
45.0     6
Name: count, dtype: int64

In [ ]:
import random
def choose_product(row):
    if (row['status'] == "Премиальный клиент") or (row['avg_monthly_balance_KZT'] >= 1_000_000*3):
        product = random.choice(vip)
        if product.endswith("card"):
            return random.choice(['Премиальная карта'])
        return product

    elif row['fx_count'] >= 12 * 3:
        product = random.choice(valut)
        if product.endswith("card"):
            return row['card']
        return product

    elif row['avg_monthly_balance_KZT'] >= 100_000 * 3:
        product = random.choice(middle)
        if product.endswith("card"):
            return row['card']
        return product

    else:
        product = random.choice(standart)
        if product.endswith("card"):
            return row['card']
        return product

client_info_sm['recommended_product'] = client_info_sm.apply(choose_product, axis=1)

In [ ]:
client_info_sm['recommended_product'].value_counts()

recommended_product
Кредитная карта           11
Инвестиции                10
Кредит наличными           8
Премиальная карта          7
Депозит Мультивалютный     6
Депозит Сберегательный     5
Золотые слитки             5
Депозит Накопительный      5
Обмен валют                3
Name: count, dtype: int64

In [ ]:
client_info_sm = pd.merge(clients[['client_code', 'name', 'age']], client_info_sm, on=['client_code'], how='left')

In [ ]:

# client_info_sm.to_excel("client_info_sm.xlsx", index=False)